language: python
python:
 - "2.7"
services:
 - docker
before_install:
 - docker build -t appserver application-server/
 - docker network create --driver=bridge --subnet=192.168.0.0/24 --gateway=192.168.0.1 mynet
 - docker run --net mynet --ip=192.168.0.10 appserver
script: 
 - pytest --cov-config .coveragerc --cov=$(pwd)
after_success: codecov --token=$CODECOV_TOKE
